### PR TITLE
Add Support for the x86 servers

### PR DESCRIPTION
**Pull request by BaptisteGerondeau**

### CODE REVIEW

**Comment by rengolin** [comment]
We should get the mirror in our local cache first, for stage 2

**Comment by rengolin** [comment]
Don't forget to document how to get PXELinux on mrp, as well as any additional manual tasks you have done to get there

**Comment by rengolin** [comment]
Otherwise, looks good, thanks!

**Comment by BaptisteGerondeau** [comment]
Now x86 machines have their local stage2 !

To fetch stage2 on the fileserver I used this command :
"rsync  -avSHP --include='**/' --include='**/{{ arch }}/**' --exclude='*' --delete rsync://{{ repo_url }}"

Concerning the pxelinux, to get it :
"wget http://ftp.debian.org/debian/dists/stretch/main/installer-amd64/current/images/netboot/debian-installer/amd64/pxelinux.0"

**Comment by rengolin** [comment]
Awesome, thanks!

**Pull request merged**
